#!/bin/bash
#
# this file is licenced under the
#
# DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                    Version 2, December 2004
#
# Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>
#
# Everyone is permitted to copy and distribute verbatim or modified
# copies of this license document, and changing it is allowed as long
# as the name is changed.
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#  0. You just DO WHAT THE FUCK YOU WANT TO.
#
#

# daemon mode
#(
# set to your liking
#WATCH_DIR=/home/ftp/FTWMirror
#TARGET_DIR=/var/www/ftw_mirror/data

WATCH_DIR=/home/keios/test
TARGET_DIR=/var/www/ftw_mirror/data


# this will be read (and cleared) by the frontend
ERROR_MSG=/var/www/ftw_mirror/error.msg

# this is cheap and only somewhat effective. webservers generally interpret files by mimetype, not by extension,
# so you really shouldn't frolic that you're safe from malicious attackers. 'malicious_php_code.jpg' can still ruin your day
EXCLUDE_TYPES="xhtml xml html htm php php4 php5 ph3 ph4 ph5 phtml phtm pl cgi"

# for setting permissions on the file afterwards - not a umask
MIRRORED_FILEPERM="0440"
# should be set to the user and group your webserver uses
MIRRORED_USER="www-data"
MIRRORED_GROUP="www-data"

# use symlinks instead of copying. will only work if $WATCH_DIR and $TARGET_DIR are on the same partition. could fail because of access rights
USE_SYMLINKS=true

# leave these alone
ACTION=""
DATE=""
FILE_HANDLE=""
FILETYPE=""

set -u
# build a suitable regexp
EXCLUDE_TYPES="^${EXCLUDE_TYPES// /\$|^}\$"
# set up error logging
[ -f "$ERROR_MSG" ] || touch "$ERROR_MSG" && chown "$MIRRORED_USER":"$MIRRORED_GROUP" "$ERROR_MSG"

# escape directories in case of weird characters
WATCH_DIR=$(printf '%q' "$WATCH_DIR")
TARGET_DIR=$(printf '%q' "$TARGET_DIR")

# main loop
inotifywait -q -m -r --format '%e %f' -e create -e delete -e close_write -e moved_to -e moved_from "$WATCH_DIR" | while read LINE; do

    ACTION=${LINE%% *}
    FILE_HANDLE=${LINE#* }

    case $ACTION in
        CREATE,ISDIR)
            # write an error message if somebody tries to upload a directory
            DATE=$(date +%F/%T)
            echo -e "$DATE: \"$FILE_HANDLE\" is a directory. this service is for files only.\r" >> "$ERROR_MSG"
            # for good measure
            rm -rf $WATCH_DIR/$FILE_HANDLE
            
        ;;
        DELETE|MOVED_FROM)
			DELETE_DIR=$(find $TARGET_DIR -name "$FILE_HANDLE" -printf %h)
            rm -rf $DELETE_DIR
        ;;
        CLOSE_WRITE*|MOVED_TO)
            FILETYPE=$(echo ${FILE_HANDLE##*.} | tr [:upper:] [:lower:])
            if [[ $FILETYPE =~ $EXCLUDE_TYPES ]]; then
                # write an error message if somebody tries to upload an undesirable filetype
                DATE=$(date +%F/%T)
                echo -e "$DATE: \"$FILE_HANDLE\" is a \"$FILETYPE\" file. this service does not accept such.\r" >> "$ERROR_MSG"
                # kill it with fire or the nearest equivalent
                rm -f "$WATCH_DIR/$FILE_HANDLE"
            else
				# make up some directory based on file checksum
				CKSUM=$(cksum "$WATCH_DIR/$FILE_HANDLE" | tr -s " " "\012" | head -1)
				mkdir "$TARGET_DIR/$CKSUM" && touch "$TARGET_DIR/$CKSUM/index.html"
				
				# escape file handle
				FILE_HANDLE=$(printf '%q' "$FILE_HANDLE")

                if ($USE_SYMLINKS); then
                    eval ln -sf "$WATCH_DIR/$FILE_HANDLE" "$TARGET_DIR/$CKSUM/$FILE_HANDLE"
                else
                    DISKFREE=$(df $TARGET_DIR | tail -1 | tr -s " " "\012" | tail -n 3 | head -1)
                    FILESIZE=$(stat -c%s $WATCH_DIR/$FILE_HANDLE)

                    if [[ $DISKFREE -gt $FILESIZE ]]; then
                        cp -f "$WATCH_DIR/$FILE_HANDLE" "$TARGET_DIR/$CKSUM/$FILE_HANDLE"
                        chmod "$MIRRORED_FILEPERM" "$TARGET_DIR/$CKSUM/$FILE_HANDLE"
                        chown "$MIRRORED_USER:$MIRRORED_GROUP" "$TARGET_DIR/$CKSUM/$FILE_HANDLE"
                    fi
                fi
            fi
        ;;
        *)
        ;;
    esac

    # just because
    ACTION=""
    FILE_HANDLE=""
    LINE=""

done
# daemon mode
#) </dev/null >/dev/null 2>&1 &
#disown

exit 0
 # just because
    ACTION=""
    FILE_HANDLE=""
    LINE=""

done
# daemon mode
#) </dev/null >/dev/null 2>&1 &
#disown

exit 0
